import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import Card from "@/components/ui/Card";
import census from "../../census.json";

// Foundations/Corpus Status — a live dashboard of the DS corpus state (design-system-quality Pillar 1.4).
// Reads `census.json` (emitted by `scripts/census.mjs --write`): classification (axis B), idiom (axis A) and
// what's missing, per piece. Quality (a11y/VRT) is added to the table once it's recorded per piece in the sweep.
// Registers no component (it documents the catalog). (ECO-197.)
const meta = {
  title: "Foundations/Corpus Status",
  parameters: { layout: "fullscreen" },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

type Row = {
  name: string;
  role: "primitive" | "composite" | null;
  onTv: boolean;
  hasSpecs: boolean;
  axes: string[];
  composes: string[];
  tvCandidate: boolean;
};

function Flag({ ok }: { ok: boolean }) {
  return ok ? (
    <span className="text-success">✓</span>
  ) : (
    <span className="text-content-tertiary">·</span>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <Card className="px-4 py-3">
      <div className="text-h2 text-content-primary">{value}</div>
      <div className="text-caption text-content-tertiary">{label}</div>
    </Card>
  );
}

export const Overview: Story = {
  render: () => {
    const rows = census.rows as Row[];
    return (
      <div className="bg-surface-secondary min-h-screen p-8">
        <div className="mx-auto max-w-5xl">
          <h1 className="text-h1 text-content-primary mb-1">Corpus Status</h1>
          <p className="text-body text-content-secondary mb-6">
            Per-piece DoD state — generated by{" "}
            <code className="text-content-primary">scripts/census.mjs</code>.
          </p>
          <div className="mb-6 grid grid-cols-2 gap-4 sm:grid-cols-4">
            <Stat label="components" value={census.total} />
            <Stat
              label="classified (B)"
              value={`${census.classified}/${census.total}`}
            />
            <Stat
              label="on tv (A)"
              value={`${census.onIdiom}/${census.total}`}
            />
            <Stat
              label="missing primitives"
              value={census.missingPrimitives.length}
            />
          </div>
          <Card size="lg" className="overflow-x-auto p-4">
            <table className="text-body w-full">
              <thead>
                <tr className="border-border-strong text-caption text-content-tertiary border-b text-left">
                  <th className="py-2 pr-4 font-normal">Component</th>
                  <th className="py-2 pr-4 font-normal">role (B)</th>
                  <th className="py-2 pr-4 font-normal">tv (A)</th>
                  <th className="py-2 pr-4 font-normal">Specs</th>
                  <th className="py-2 pr-4 font-normal">axes</th>
                  <th className="py-2 pr-4 font-normal">composes</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.name} className="border-border-subtle border-b">
                    <td className="text-content-primary py-1.5 pr-4">
                      {r.name}
                    </td>
                    <td className="py-1.5 pr-4">
                      {r.role ? (
                        <span className="text-content-secondary">{r.role}</span>
                      ) : (
                        <span className="text-warning">unclassified</span>
                      )}
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.onTv} />
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.hasSpecs} />
                    </td>
                    <td className="text-content-tertiary py-1.5 pr-4">
                      {r.axes.join(", ") || "—"}
                    </td>
                    <td className="text-content-tertiary py-1.5 pr-4">
                      {r.composes.join(", ") || "—"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        </div>
      </div>
    );
  },
};
