import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import Card from "@/components/ui/Card";
import census from "../../census.json";

// Foundations/Corpus Status — a live dashboard of the DS corpus state (design-system-quality Pillar 1.4).
// Reads `census.json` (emitted by `scripts/census.mjs --write`): classification (axis B), idiom (axis A) and
// what's missing, per piece. Quality (a11y/VRT) is added to the table once it's recorded per piece in the sweep.
// Registers no component (it documents the catalog). (ECO-197.)
const meta = {
  title: "Foundations/Corpus Status",
  parameters: { layout: "fullscreen" },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

type Row = {
  name: string;
  role: "primitive" | "composite" | null;
  onTv: boolean;
  hasSpecs: boolean;
  axes: string[];
  composes: string[];
  tvCandidate: boolean;
  // Model B (ECO-198): colocación + estado por-paso de la DoD.
  placement: "Migration" | "Primitives" | "Composite" | "Layout" | null;
  dod: { A: boolean; B: boolean; F: boolean; Q: boolean; O: boolean };
  certified: boolean;
  certifiable: boolean;
};

function Flag({ ok }: { ok: boolean }) {
  return ok ? (
    <span className="text-success">✓</span>
  ) : (
    <span className="text-content-tertiary">·</span>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <Card className="px-4 py-3">
      <div className="text-h2 text-content-primary">{value}</div>
      <div className="text-caption text-content-tertiary">{label}</div>
    </Card>
  );
}

export const Overview: Story = {
  render: () => {
    const rows = census.rows as Row[];
    return (
      <div className="bg-surface-secondary min-h-screen p-8">
        <div className="mx-auto max-w-5xl">
          <h1 className="text-h1 text-content-primary mb-1">Corpus Status</h1>
          <p className="text-body text-content-secondary mb-6">
            Per-piece DoD state — generated by{" "}
            <code className="text-content-primary">scripts/census.mjs</code>.
          </p>
          <div className="mb-6 grid grid-cols-2 gap-4 sm:grid-cols-4">
            <Stat label="components" value={census.total} />
            <Stat
              label="in Migration (WIP)"
              value={`${census.inMigration}/${census.total}`}
            />
            <Stat
              label="certified (Primitives/Composite)"
              value={census.certified}
            />
            <Stat label="ready to promote" value={census.readyToPromote} />
          </div>
          <Card size="lg" className="overflow-x-auto p-4">
            <table className="text-body w-full">
              <thead>
                <tr className="border-border-strong text-caption text-content-tertiary border-b text-left">
                  <th className="py-2 pr-4 font-normal">Component</th>
                  <th className="py-2 pr-4 font-normal">placement</th>
                  <th className="py-2 pr-4 font-normal">A · contract</th>
                  <th className="py-2 pr-4 font-normal">B · role</th>
                  <th className="py-2 pr-4 font-normal">F · fidelity</th>
                  <th className="py-2 pr-4 font-normal">a11y</th>
                  <th className="py-2 pr-4 font-normal">O · org</th>
                  <th className="py-2 pr-4 font-normal">ready</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.name} className="border-border-subtle border-b">
                    <td className="text-content-primary py-1.5 pr-4">
                      {r.name}
                    </td>
                    <td className="py-1.5 pr-4">
                      {r.certified ? (
                        <span className="text-success">{r.placement}</span>
                      ) : r.placement === "Migration" ? (
                        <span className="text-warning">Migration</span>
                      ) : (
                        <span className="text-content-tertiary">
                          {r.placement ?? "—"}
                        </span>
                      )}
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.dod.A} />
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.dod.B} />
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.dod.F} />
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.dod.Q} />
                    </td>
                    <td className="py-1.5 pr-4">
                      <Flag ok={r.dod.O} />
                    </td>
                    <td className="py-1.5 pr-4">
                      {/* certificada pero incompleta = fallo del gate check-piece-complete */}
                      {r.certified && !r.certifiable ? (
                        <span className="text-error">✗ gate</span>
                      ) : r.certifiable ? (
                        <span className="text-success">✓</span>
                      ) : (
                        <span className="text-content-tertiary">·</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        </div>
      </div>
    );
  },
};
