-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'TENANT_INVITATION_ACCEPTED';
ALTER TYPE "AuditAction" ADD VALUE 'TENANT_INVITATION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'TENANT_INVITATION_EMAIL_MISMATCH_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE 'TENANT_INVITATION_EXPIRE_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE 'TENANT_INVITATION_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE 'TENANT_MEMBERSHIP_CREATED';
